name: PChome Price Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '13 21 * * *'
    - cron: '27 03 * * *'
    - cron: '42 11 * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - name: 檢查程式碼
      uses: actions/checkout@v3

    - name: 設定 Python 環境
      uses: actions/setup-python@v4
      with:
        python-python-version: '3.10'

    - name: 安裝 Chrome 瀏覽器
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: 安裝 Python 套件
      run: |
        pip install requests DrissionPage bs4

    - name: 執行監控爬蟲
      env:
        LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        MY_USER_ID: ${{ secrets.MY_USER_ID }}
      run: python monitor.py
